baseurl: ''
url: 'https://trabajoescrito.com'
name: 'trabajoescrito.com'
author: Julian Franco
email: https://sendfox.com/trabajoescrito
pinterest_url: https://co.pinterest.com/trabajoescrito/

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

collections:
  pages:
    output: true
    permalink: /:path