baseurl: ''
url: 'https://trabajoescrito.com.co'
name: 'trabajoescrito.com'
author: Julian Franco
email: contacto@trabajoescrito.com.co
# facebook_url: 
# twitter_url: https://twitter.com/bloglaterminal
# linkedin_url: 
pinterest_url:
instagram_url: https://www.instagram.com/terminaldetransporte/
# rss_url:

markdown: kramdown

permalink: :slug

keep_files: [/img]

compress_html:
    clippings: []
    comments: []
    endings: []
    ignore:
    envs: []
    blanklines: false
    profile: false
    startings: []

plugins:
  - jekyll-sitemap

