# config.yml

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'site/img/blog'
public_folder: '/img/blog'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'default' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'H1', name: 'h1', widget: 'string' }
      - { label: 'Intro', name: 'intro', widget: 'string' }
      - { label: 'Boton Info', name: 'boton_info', widget: 'string', default: 'estructura' }
      - { label: 'Boton Info Nombre', name: 'boton_info_title', widget: 'string' }
      - { label: 'Boton Descargas', name: 'boton_mas', widget: 'string', default: 'descargas' }
      - { label: 'Boton Descargas Nombre', name: 'boton_mas_title', widget: 'string' }
      - { label: 'Type', name: 'vertical', widget: 'boolean', default: 'true' }